### ISSUE TITLE
字体大小问题

### ISSUE THREAD

**Issue by skydai** [shixiaohu2206/hexo-theme-huhu#18]
Chrome MacOS
个人建议，感觉markdown主体的话字体大小调到120%看起来比较舒适。然后可以将主体部分的宽度调到900px 或者800px，现在是700px

``` css
#container {
    display-flex()
    justify-content(center)
    width: 100%
    padding: 0.3rem
    box-sizing: border-box
    position: absolute
    overflow: hidden

    .main {
        display-flex()
        flex-direction(column)
        justify-content(center)
        box-sizing: border-box
        width: 100%
        max-width: 700px
        padding: 2rem
   }
.......
}
```
