### ISSUE TITLE
window.THEME_CONFIG = JSON.parse('<%- JSON.stringify(theme) %>') causes syntax error if theme contains single quotation mark '

### ISSUE THREAD

**Issue by lirc572** [shixiaohu2206/hexo-theme-huhu#2]
If deploy options  in _config.yml are set as: (contains single quotes)
```
deploy:
  type: git
  repo: git@repo:repo.repo.git
  branch: master
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
```
The following line (line226 of layout.ejs) will cause error since the quotation marks are not escaped.
```
window.THEME_CONFIG = JSON.parse('<%- JSON.stringify(theme) %>') 
```
